Allow use of --imply_local when calling DiffviewOpen, allowing LSP use and linting in MR review
harrisoncramer/gitlab.nvim pull request #162
Opened 2024-01-15 17:22 UTC by d-karl

After this MR, gitlab.nvim will attempt to use --imply_local parameter when opening diffview reviewer, based on a new configuration setting for gitlab.nvim, which is introduced as an "opt-in" option. Previous behavior is unchanged unless gitlab.nvim is configured by user to use the new feature.

The benefit of --imply_local is that diffview will treat the current HEAD that is being reviewed as a local file, allowing full use of diagnostics in the buffer, including LSP and linters.

In case the local working tree has changes compared to the state that is being reviewed, gitlab.nvim will not use the --imply_local parameter towards diffview, because that would could potentially show local file changes which are not part of the merge request under review. In this case a warning will be dispatched, and the usual reviewer is opened, as it is without the gitlab.nvim option active.

Potential issues:
1. Stability of diffivew API and the "--imply_local" option.
2. Reliance on "cwd == git root" when checking for local changes to files.
3. It appears currently currently diffview does not set the buffer to "readonly" when --imply_local is used. This may be something to ask for a fix in their code. I find it odd that "reviewing and implying local" does not "write_protect" the window.

Created after discussion in https://github.com/harrisoncramer/gitlab.nvim/issues/156.

2024-01-16 20:01 UTC, harrisoncramer requested changes
Left a few comments, thanks for doing this!

2024-01-16 20:01 UTC, harrisoncramer commented on lua/gitlab/reviewer/diffview.lua
> +  vim.api.nvim_command(string.format("%s %s..%s", diffview_open_command, diff_refs.base_sha, diff_refs.head_sha))
When using a messenger tool like [notify](https://github.com/rcarriga/nvim-notify), the message is lost when switching tabs. We want to flash the warning after the reviewer changes tabs, so you'd have to store it in a variable:

```lua
  local has_unmodified_files = are_git_managed_files_modified()
  if state.settings.reviewer_settings.diffview.imply_local and not has_unmodified_files then
    diffview_open_command = diffview_open_command .. " --imply-local"
  end

  -- The code to open the reviewer in a new tab...

  if has_unmodified_files and state.settings.reviewer_settings.diffview.imply_local then
    u.notify(
      "There are uncommited changes in the working tree, cannot use 'imply_local' setting for gitlab reviews. Stash or commit all changes to use.",
      vim.log.levels.WARN
    )
  end
```

2024-01-16 23:02 UTC, d-karl commented on lua/gitlab/reviewer/diffview.lua
> +  local status_result = vim.system({ "git", "status", "--short", "--untracked-files=no" }, { text = true }):wait()
Ooh, thanks for raising this. I relied on the docs without too much thinking. In neovim nightly the [doc](https://github.com/neovim/neovim/blob/master/runtime/doc/builtin.txt#L8165) for `vim.fn.system` states: "prefer `vim.system` in lua", so I figured that is a deprecation notice that has been there for a while, when in fact I guess it is very recent and supposed to happen in 0.10.

I'll change it to use the existing 0.9 API, sure!

2024-01-20 00:33 UTC, d-karl commented
Thank you for the previous round of comments. I made changes to trigger notification after the tab switch and use the older `system` function for better compatibility.

For better locality and readability, I rewrote the feature-specific control flow a bit. I'm not sure what the merge strategy is on this pull request. For sake of easy review, I made very granular commits.

2024-01-20 23:04 UTC, harrisoncramer approved these changes

2024-01-20 23:06 UTC, merged